# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83ba9c5e2004c385fc758ee421df7e7d774f041858e92929e61832530a81d9c531d9b55066cc10ae156069934d889a0734cc909308058458566ce18702e2ca68

test:
  secret_key_base: d2883cff7543728c73403a01d2a02058b3cbe4016aff6a9aea7584f4134f5b639aa98dced91d75519f32a2954aa39321ab37474ac76f70bcf16c500c7552997f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
